### ISSUE TITLE
Current demos do not compile with C++17

### ISSUE THREAD

**Issue by knoepfel** [marcpaterno/gallery-demo#4]
CMake has trouble finding the correct compiler driver whenever building the demos.  In addition, the CMakeLists.txt file should probably be adjusted to support C++17.  I've had to make the following changes to get things to compile:

```diff
- set_property(TARGET demo PROPERTY CXX_STANDARD 14)
+ set_property(TARGET demo PROPERTY CXX_STANDARD 17)
```

If using GCC

```diff
+ SET(CMAKE_C_COMPILER $ENV{GCC_FQ_DIR}/bin/gcc)
+ SET(CMAKE_CXX_COMPILER $ENV{GCC_FQ_DIR}/bin/g++)
```

If using Clang

```diff
+ SET(CMAKE_C_COMPILER $ENV{CLANG_FQ_DIR}/bin/clang)
+ SET(CMAKE_CXX_COMPILER $ENV{CLANG_FQ_DIR}/bin/clang++)
```

I may be able to make a pull request with the appropriate changes once I have the opportunity.

**Comment by marcpaterno** [comment]
I will modify the README.md file to indicate how to control the C and C++ compilers from the *cmake* command line, and put the C++ language standard specification into the CMakeLists.txt file.

Thanks for the suggestions!
